export const getInputStyle = () => {
  return `
    input[type="button"],
    select,
    button {
      cursor: pointer;
      background-color: rgba(55, 55, 55);
      color: rgba(225, 225, 225);
      border: 1px solid rgb(105, 105, 105);
      border-radius: 24px;
      padding: 0.5em 1em;
    }

    /**
     * Generated by danielstern.ca/range.css/#/
     * 
     * Some manual tweaks
     */
    input[type=range] {
      -webkit-appearance: none;
      margin: 0px 0;
      background-color: transparent;
    }

    input[type=range]:focus {
      outline: none;
    }

    input[type=range]::-webkit-slider-runnable-track {
      /** disabled because of vertical sliders: width: 100%; */
      height: 16px;
      cursor: pointer;
      box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2);
      background-color: rgba(55, 55, 55);
      border-radius: 25px;
      border: 0px solid #000000;
    }

    input[type=range]::-webkit-slider-thumb {
      box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2);
      border: 1px solid rgb(45, 45, 45);
      height: 16px;
      width: 32px;
      border-radius: 50px;
      background: rgb(255, 164, 28);
      cursor: pointer;
      -webkit-appearance: none;
      margin-top: 0px;
    }

    input[type=range].vertical-range::-webkit-slider-runnable-track,
    input[type=range].vertical-range::-webkit-slider-thumb {
      box-shadow: -2px 0 4px 0 rgba(0, 0, 0, 0.2);
    }

    input[type=range]:focus::-webkit-slider-runnable-track {
      background: #ffffff;
    }
  `;
}